# Soft Mist Inhaler Product
name = "SMI_K1"
device_type = "SMI"
formulation_type = "aqueous_solution"

# Dose and concentration
label_claim_mg = 0.025
concentration_mg_ml = 0.25

# Particle characteristics (SMI produces fine droplets)
mass_median_diameter_um = 5.8
geometric_standard_deviation = 1.4

# Device performance (high fine particle fraction)
emitted_dose_percent = 90.0
fine_particle_fraction = 0.68

# Excipients
excipients = ["water", "benzalkonium_chloride", "EDTA"]

# Metadata
description = "Soft mist inhaler with fine droplet generation"
manufacturer = "Mist_Technologies"