# Full Modular PBBM Example: Lung + GI + PK
# This configuration demonstrates complete absorption pathway including
# lung absorption, GI transit (from mucociliary clearance), and systemic PK

[run]
stages = ["deposition", "pbbm", "pk"]
seed = 456
threads = 4
enable_numba = true
artifact_dir = "full_pbbm_results"

[population_variability]
demographic = false
lung_regional = false
lung_generation = false
gi = false
pk = false
inhalation = false

[deposition]
model = "clean_lung"
particle_grid = "fine"  # Higher resolution for comprehensive modeling

[pbbm]
# Use full chained model with all components
model = "chained_full"
epi_layers = [3, 3, 2, 1]  # More epithelial layers for detailed absorption

[pbbm.solver]
method = "BDF"
rtol = 1e-7
atol = 1e-10
max_step = 1800.0  # 30-minute max step for detailed kinetics

# Lung-specific parameters
[pbbm.lung]
dissolution_cutoff_radius_cm = 5e-7  # 0.5 Î¼m cutoff
lumping_rate_per_s = 1e-3  # Faster lumping for small particles
mucus_velocity_cm_per_s = 1e-3  # Mucociliary transport rate

# GI-specific parameters  
[pbbm.gi]
n_compartments = 9  # Standard GI compartment model
peff_gi_cm_per_s = 1e-4  # GI permeability
hepatic_extraction_fraction = 0.1  # First-pass metabolism
fu_gi = 1.0  # Fraction unbound in GI

# GI transit times (stomach through colon)
[pbbm.gi.transit_times_h]
stomach = 1.0
duodenum = 0.25
jejunum_1 = 0.5
jejunum_2 = 0.5
ileum_1 = 1.0
ileum_2 = 1.0
cecum = 2.0
colon_1 = 8.0
colon_2 = 12.0

# Systemic PK parameters
[pbbm.pk]
clearance_L_per_h = 45.0
volume_central_L = 60.0
volume_peripheral1_L = 120.0
volume_peripheral2_L = 300.0
distribution_half_life_h = 1.5
fu_plasma = 0.9  # Fraction unbound in plasma

[pk]
model = "null"  # PK handled by chained PBBM

[analysis]
bioequivalence = true
custom_metrics = [
    "lung_retention", 
    "gi_absorption", 
    "total_systemic_exposure",
    "regional_concentration_profiles",
    "binding_state_analysis"
]

# Comprehensive output options
[analysis.output]
include_all_binding_states = true  # bound, unbound, total
include_solid_drug_data = true     # particle dissolution tracking
include_flux_data = true           # transport, binding, clearance fluxes
time_resolution_minutes = 1        # High temporal resolution

# Entity references
[subject]
ref = "adult_70kg"

[api]
ref = "budesonide"  # More complex molecule with significant binding

[product]
ref = "DPI_capsule"  # Different delivery device

[maneuver]
ref = "deep_DPI_inhale"
