# PK parameter sweep example
# Base configuration for exploring PK parameter space

[run]
stages = ["deposition", "pbbm", "pk"]
seed = 100
threads = 4
enable_numba = true
artifact_dir = "pk_sweep_results"

[population_variability]
demographic = false
lung_regional = false
lung_generation = false
gi = false
pk = false
inhalation = false

[deposition]
model = "clean_lung"

[pbbm]
model = "classic_pbbm"
epi_layers = [3, 3, 2, 1]

[pbbm.solver]
method = "BDF"
rtol = 1e-7
atol = 1e-10

[pk]
model = "pk_2c"

# Base PK parameters (will be swept in manifest)
[pk.params]
CL = 20.0      # Clearance (L/h)
Vc = 40.0      # Central volume (L)  
k12 = 0.5      # Central to peripheral rate (1/h)
k21 = 0.3      # Peripheral to central rate (1/h)
ka = 1.2       # Absorption rate (1/h)

[analysis]
bioequivalence = true
custom_metrics = ["lung_residence_time", "regional_exposure"]

[subject]
ref = "adult_70kg"

[api]
ref = "salbutamol"

[product]
ref = "HFA_MDI_PT210"

[maneuver]
ref = "standard_MDI_inhale_hold"
