# FEV1 Study Configuration Parameters
# Default study design parameters for FEV1 efficacy trials

name = "fev1_study_config_default"
description = "Default study configuration for FEV1 efficacy trials"

# Trial design parameters
n_trials = 200                     # Number of trial simulations
trial_size = 204                   # Study arm size (subjects per arm)
trial_duration_weeks = 24          # Trial duration [weeks]

# Study type specifications
study_type = "copd_efficacy"       # Study type identifier
primary_endpoint = "fev1_change"   # Primary efficacy endpoint

# Statistical parameters
confidence_level = 0.95            # Confidence level for intervals
alpha_level = 0.05                 # Alpha level for significance testing

# Alternative configurations (commented for reference)
# [alternative_config]
# n_trials = 100                   # Smaller trial count for testing
# trial_size = 240                 # Alternative arm size 
# trial_duration_weeks = 12        # Shorter trial duration